version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    user: "1000:1000"
    ports:
      - "1883:1883"  # MQTT port

  influxdb:
    image: influxdb:2.7-alpine
    volumes:
    - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=measurement_db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_REPORTING_DISABLED=true
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=waga
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token123

  grafana:
    image: grafana/grafana:8.4.1
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - INFLUXDB_TOKEN=token123
      - INFLUXDB_BUCKET=waga
      - INFLUXDB_ORG=org

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb_data: {}
  grafana_data: {}
